### ISSUE TITLE
Incorrect URL for MeiliSearch + React InstantSearch demo in README

### ISSUE THREAD

**Issue by shivaylamba** [meilisearch/demos#12]
The URL for MeiliSearch + React InstantSearch redirects to the Angular MS Demo. 
The correct url is : https://codesandbox.io/s/ms-react-is-sh9ud?fontsize=14&hidenavigation=1&theme=dark

**Comment by shivaylamba** [comment]
I can take up the issue @ferdi05

**Comment by ferdi05** [comment]
yes please go ahead
