### ISSUE TITLE
Add `where2watch` demo

### ISSUE THREAD

**Issue by mdubus** [meilisearch/demos#120]
Since the demo-movies is now public on GitHub, we should add it to the list of the available demos.

**Demo repo**: [https://github.com/meilisearch/demo-movies](https://github.com/meilisearch/demo-movies)

**Live demo**: [https://where2watch.meilisearch.com/](https://where2watch.meilisearch.com/)

**Comment by nooras** [comment]
Hi @mdubus, @CaroFG,

I am interested in this issue.
Can you please assign it to me?
I have one question. This need to be add in readme file, correct?

Waiting for your response.

Thanks :)

**Comment by aniketh-varma** [comment]
Hi @mdubus @CaroFG, I would like to take this issue if it is still available for grabs.

**Comment by CaroFG** [comment]
Hey @nooras and @aniketh-varma, as stated in [the CONTRIBUTING guidelines](https://github.com/meilisearch/demos/blob/main/CONTRIBUTING.md):

> There will be no issue assignment as we don’t want people to ask to be assigned specific issues and never return, discouraging the volunteer contributors from opening a PR to fix this issue. We take the liberty to choose the PR that best fixes the issue, so we encourage you to get to it as soon as possible and do your best!
