### ISSUE TITLE
Adding a link to Matching Strategy documentation in the Matching Strategy demo

### ISSUE THREAD

**Issue by shivaylamba** [meilisearch/demos#130]
The matching strategy demo is really great! 
But I was just wondering if we could add a small icon to navigate to the documentation for Matching strategy demo. 

If someone lands on the demo and wants to also learn about matching strategy it would be beneficial. 
We also had a section for learn more about tenant token in the tenant token demo (https://tenant-token.meilisearch.com/)

cc @ferdi05 @CaroFG

**Comment by CaroFG** [comment]
Great idea!

**Comment by viveknshah** [comment]
Looking for a similar footer in the app that points to https://docs.meilisearch.com/reference/api/search.html#search-parameters ?

**Comment by CaroFG** [comment]
It should point to: https://docs.meilisearch.com/reference/api/search.html#matching-strategy

It doesn't necessarily have to be a footer
