### ISSUE TITLE
Need to authorise Vercel deployment for PR created by developers not having access to the organization Vercel

### ISSUE THREAD

**Issue by shivaylamba** [meilisearch/demos#43]
![image](https://user-images.githubusercontent.com/19529592/164466532-89d6c7dd-09fe-45ff-a820-d9f166c69eb5.png)
At the moment any PR not created by me in the demos, repo says that the check for the tenant token demo in vercel needs to be verified by the authorized person and the check fails. 
While for other demos it works fine

**Comment by nicolasvienot** [comment]
Hey @meilisearch/devrel-team, did it fix your issue?

**Comment by shivaylamba** [comment]
This should be fixed, since I followed the steps as suggested by @nicolasvienot to configure the setting in Vercel for the project.

**Comment by nicolasvienot** [comment]
Hi @meilisearch/devrel-team,

After a talk with @CaroFG I wanted to get back to this issue and the way we handled it.
Be aware that disabling the `Git Fork Protection` on Vercel might cause security issue if you have the same environment variables in your `preview`, `staging` and `production` environment.

It means that anyone can trigger a deployment in `Preview mode` by creating a PR in this repository, and this PR will have access to your environment variables. If there is any sensitive information there (Meilisearch master key or private key for example), you should either only use them in production or find another way to handle them. Let me know if you need any help with that.

[See vercel post here](https://vercel.com/changelog/git-fork-protection-can-now-be-disabled)
