### ISSUE TITLE
Update Meilisearch logo on Pypi demo

### ISSUE THREAD

**Issue by CaroFG** [meilisearch/demos#61]

**Comment by AyushK-101** [comment]
I would like to work on this issue

**Comment by CaroFG** [comment]
Hi @AyushK-101 !!! Thank you for your interest in Meilisearch, as stated in our [contributing guidelines](https://github.com/meilisearch/demos/blob/main/CONTRIBUTING.md#hacktoberfest-2022):

> There will be no issue assignment as we don’t want people to ask to be assigned specific issues and never return, discouraging the volunteer contributors from opening a PR to fix this issue. We take the liberty to choose the PR that best fixes the issue, so we encourage you to get to it as soon as possible and do your best!
