### ISSUE TITLE
e-commerce deploy fails on Vercel

### ISSUE THREAD

**Issue by mdubus** [meilisearch/demos#89]
FYI @shivaylamba 

The deployment of the e-commerce demo fails on Vercel. See [here](https://github.com/meilisearch/demos/issues/new).

<img width="1030" alt="Capture d’écran 2022-06-09 à 17 10 22" src="https://user-images.githubusercontent.com/30866152/172881190-3d933672-fc62-4b0d-ae0f-bd98653bfe36.png">

In order to fix the issue, you need to add `"sourceType": "module"` in the `.eslintrc.json` file:
```js
 "parserOptions": {
    "sourceType": "module",
    "ecmaVersion": 12
  },
```

But then, it raises other errors because eslint is still not configured properly: 

<img width="865" alt="Capture d’écran 2022-06-09 à 17 54 26" src="https://user-images.githubusercontent.com/30866152/172891278-4f107d7a-484c-4d3e-8442-a3a52ae066d6.png">

In order to fix it, you need to do the following:

- Addition of `next` in the `extends` list of the `.eslintrc.json` file:
```js
"extends": ["next", "eslint:recommended", "plugin:prettier/recommended"],
```

- Update of the eslint scripts in the `package.json` file in order to lint the `JSX` files and not only the `JS` ones:
```js
    "lint": "eslint --ext .js,.jsx .",
    "lint:fix": "eslint --ext .js,.jsx . --fix",
```

Then the linter should finally run correctly and raise a lot of errors in the `JSX` files: 

<img width="868" alt="Capture d’écran 2022-06-09 à 17 57 21" src="https://user-images.githubusercontent.com/30866152/172891806-abbd5bbe-eb19-4c9c-9051-1658a9b7ac25.png">

By running `npm run lint:fix` it should fix the majority of these linter issues (quotes, semicolons, ...)

Only 2 warning are still present and can be fixed manually: 

<img width="868" alt="Capture d’écran 2022-06-09 à 17 58 39" src="https://user-images.githubusercontent.com/30866152/172892111-21233b41-74bc-40bf-9c82-c1fcdff7eb23.png">

**Comment by shivaylamba** [comment]
Thank you @mdubus I have made the necessary changes in the PR.
