### ISSUE TITLE
Geo-javascript demo: can't delete everything from the search bar

### ISSUE THREAD

**Issue by irevoire** [meilisearch/demos#9]
Hello,

I was looking at the [geo-javascript / all-countries](https://github.com/meilisearch/demos/tree/main/src/geo-javascript) demo [here](https://codesandbox.io/s/instant-meilisearch-geo-search-6c96p), and I noticed that if I search for « Lille », and then frenetically press my delete key until nothing is left in the search bar, the demo is still searching for « L », see the following picture:
![image](https://user-images.githubusercontent.com/7032172/147083374-3e114d50-b2b4-42de-80c0-8c9ddcc96dfa.png)

**Comment by viveknshah** [comment]
Weird, I wasn't able to recreate this issue. Worked as expected for me in the same environment as mentioned
> tried with backspace and delete incase there were different behaviour
> tried with 3 different names for the above 2 behaviours

**Comment by nooras** [comment]
I also tried to replicate this issue. It seems its already fixed.

**Comment by CaroFG** [comment]
Thank you! Closing this then, feel free to reopen if the problem rearises 🙏

**Comment by ferdi05** [comment]
possibly a bug that disappeared as we updated the Meilisearch versions (this one is supposed to run on v0.28 or 0.29 now thanks to @oluademola )
