### ISSUE TITLE
Add a .gitignore file in the base directory  

### ISSUE THREAD

**Issue by shivaylamba** [meilisearch/demos#96]

**Comment by CaroFG** [comment]
As discussed [here](https://github.com/meilisearch/demos/issues/79#issuecomment-1141923905)

**Comment by mohitsaxenaknoldus** [comment]
Which kind of files are we trying to avoid?

**Comment by CaroFG** [comment]
Hey! Since each project folder has its own `.gitignore` file, we are trying to avoid very general operation system or IDE related files
